#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=$(which eww)

close_dash() {
  ${EWW} --config "$CFG" close \
    background profile system clock uptime music github \
    reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
  rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
  close_dash && firefox &

elif [[ "$1" == "--sp" ]]; then
  close_dash && spotify-launcher &

elif [[ "$1" == "--ob" ]]; then
  close_dash && obsidian &

elif [[ "$1" == "--tr" ]]; then
  close_dash && alacritty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
  close_dash && thunar ~ &

elif [[ "$1" == "--ge" ]]; then
  close_dash && geany &

elif [[ "$1" == "--cd" ]]; then
  close_dash && code &

elif [[ "$1" == "--gc" ]]; then
  close_dash && galculator &

elif [[ "$1" == "--zb" ]]; then
  close_dash && zen-browser &

fi
